# Generated by Django 6.0.3 on 2026-03-27 05:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('tipo_doc', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('LC', 'L.C.'), ('LE', 'L.E.'), ('CUIT', 'CUIT')], default='DNI', max_length=20, verbose_name='Tipo de documento')),
                ('nro_doc', models.CharField(blank=True, max_length=50, verbose_name='Nro. de documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('BRL', 'Reales (BRL)')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_DEB', 'Tarjeta de Débito'), ('TARJETA_CRED', 'Tarjeta de Crédito'), ('CHEQUE', 'Cheque'), ('MERCADOPAGO', 'MercadoPago'), ('OTRO', 'Otro')], max_length=20, verbose_name='Forma de pago')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referencia / Nro. comprobante')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('AEROLINEA', 'Aerolínea'), ('HOTEL', 'Hotel'), ('CRUCERO', 'Crucero'), ('AGENCIA', 'Agencia Mayorista'), ('TRASLADO', 'Traslado'), ('SEGURO', 'Seguro de Viaje'), ('EXCURSION', 'Excursión'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Recibo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.cliente', verbose_name='Cliente')),
                ('cobros', models.ManyToManyField(to='agencia.cobro', verbose_name='Cobros incluidos')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Reserva')),
                ('tipo_servicio', models.CharField(choices=[('VUELO', 'Vuelo'), ('HOTEL', 'Hotel'), ('PAQUETE', 'Paquete Turístico'), ('CRUCERO', 'Crucero'), ('TRASLADO', 'Traslado'), ('SEGURO', 'Seguro de Viaje'), ('EXCURSION', 'Excursión'), ('OTRO', 'Otro')], default='PAQUETE', max_length=20, verbose_name='Tipo de servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('fecha_regreso', models.DateField(blank=True, null=True, verbose_name='Fecha de regreso')),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de costo')),
                ('moneda_costo', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('BRL', 'Reales (BRL)')], default='ARS', max_length=3, verbose_name='Moneda costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de venta')),
                ('moneda_venta', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('BRL', 'Reales (BRL)')], default='ARS', max_length=3, verbose_name='Moneda venta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('nro_reserva_proveedor', models.CharField(blank=True, max_length=100, verbose_name='Nro. reserva proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='agencia.cliente', verbose_name='Cliente titular')),
                ('pasajeros_adicionales', models.ManyToManyField(blank=True, related_name='reservas_como_pasajero', to='agencia.cliente', verbose_name='Pasajeros adicionales')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('BRL', 'Reales (BRL)')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_DEB', 'Tarjeta de Débito'), ('TARJETA_CRED', 'Tarjeta de Crédito'), ('CHEQUE', 'Cheque'), ('MERCADOPAGO', 'MercadoPago'), ('OTRO', 'Otro')], max_length=20, verbose_name='Forma de pago')),
                ('referencia', models.CharField(blank=True, max_length=200, verbose_name='Referencia / Nro. comprobante')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedor', to='agencia.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cobro',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='agencia.reserva', verbose_name='Reserva'),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nro. Voucher')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('notas_voucher', models.TextField(blank=True, verbose_name='Notas en el voucher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
