# Generated by Django 6.0.3 on 2026-03-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)'),
        ),
    ]
