# Generated by Django 6.0.3 on 2026-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_proveedor_comision_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoproveedor',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante'),
        ),
    ]
