# Generated by Django 6.0.3 on 2026-04-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0007_cliente_foto_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_DEB', 'Tarjeta de Débito'), ('TARJETA_CRED', 'Tarjeta de Crédito'), ('CHEQUE', 'Cheque'), ('MERCADOPAGO', 'MercadoPago'), ('DEPOSITO', 'Depósito Bancario'), ('OTRO', 'Otro')], max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_DEB', 'Tarjeta de Débito'), ('TARJETA_CRED', 'Tarjeta de Crédito'), ('CHEQUE', 'Cheque'), ('MERCADOPAGO', 'MercadoPago'), ('DEPOSITO', 'Depósito Bancario'), ('OTRO', 'Otro')], max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('AEROLINEA', 'Aerolínea'), ('HOTEL', 'Hotel'), ('CRUCERO', 'Crucero'), ('AGENCIA', 'Agencia Mayorista'), ('OPERADOR', 'Operador Mayorista'), ('TRASLADO', 'Traslado'), ('SEGURO', 'Seguro de Viaje'), ('EXCURSION', 'Excursión'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(max_length=200, verbose_name='Nombre del paquete')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('lugar_salida', models.CharField(max_length=200, verbose_name='Lugar de salida')),
                ('pasa_por_jardin_america', models.BooleanField(default=False, verbose_name='Pasa por Jardín América')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción / Itinerario')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio')),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('BRL', 'Reales (BRL)')], default='ARS', max_length=3, verbose_name='Moneda')),
                ('cupos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupos disponibles')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operadora', models.ForeignKey(blank=True, limit_choices_to={'activo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='agencia.proveedor', verbose_name='Operadora')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'ordering': ['fecha_salida'],
            },
        ),
    ]
