# Generated by Django 6.0.3 on 2026-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0008_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='salidas/', verbose_name='Foto del paquete'),
        ),
        migrations.AddField(
            model_name='salida',
            name='servicios_incluidos',
            field=models.TextField(blank=True, help_text='Un servicio por línea. Ej: Traslado de ida y vuelta\nAlojamiento en hotel 3 estrellas\nDesayuno incluido', verbose_name='Servicios incluidos'),
        ),
    ]
