# Generated by Django 6.0.3 on 2026-04-11 15:06

import agencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0009_salida_foto_salida_servicios_incluidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='agotado',
            field=models.BooleanField(default=False, verbose_name='Agotado'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cupos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lugares disponibles'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=agencia.models._sanitizar_nombre_foto, verbose_name='Foto del paquete'),
        ),
    ]
