# Generated by Django 6.0.3 on 2026-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0010_add_agotado_to_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='vacaciones_invierno',
            field=models.BooleanField(default=False, verbose_name='Vacaciones de invierno'),
        ),
    ]
